---
- name: Install elk stack
  hosts: all
  become: yes
- name: setup prerequisites
  hosts: all
  become: yes
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/prerequisites'
- name: setup prerequisites
  hosts: all
  become: yes
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/elastic_key_repo'
- name: install elasticsearch
  hosts: all
  become: yes
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/elasticsearch_install'
#- name: Elasticsearch configuration
#  hosts: all
#  become: yes
#  roles:
#    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/elastic_config'
- name: install kibana
  hosts: all
  become: yes
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/kibana_install'
- name: install logstash
  hosts: all
  become: yes
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/logstash_install'
- name: install filebeat
  hosts: all
  become: true
  roles:
    - role: '/home/ec2-user/ansible/elk_install_ansible/roles/filebeat_install'

