---
# tasks file for kibana_install
- name: install kibana
  yum:
    name: kibana
    state: present
    update_cache: yes
- name: Install firewalld
  yum:
        name: firewalld
        state: latest
  notify:
        - start firewalld
- name: start firewalld
  service:
        name: firewalld
        state: started
        enabled: yes
  become: yes
- name: enable 5601
  firewalld:
        zone: public
        port: 5601/tcp
        permanent: true
        state: enabled
        immediate: true
  become: yes
- name: Kibana configuration
  copy:
      src: /home/ec2-user/ansible/elk_install_ansible/config/kibana.yml
      dest: /etc/kibana
- name: ensure kibana is running
  systemd: state=started name=kibana

